version: '3.3'

services:
  nginx:
    build: .
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/sites:/etc/nginx/sites
      - ./cache:/data/nginx/cache
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "443:443"